### ISSUE TITLE
Installing KLE Placer from PCM in KiCAD 7.0.8 does not work.

### ISSUE THREAD

**Issue by Iipal** [zykrah/kicad-kle-placer#11]
Hello, just as the title says.

After installing it via Plugin Manager, there is no icon in upper toolbar, and it's not showing under Tools menu -> External Plugins.

Restarting KiCAD and hitting Refresh Plugins button does not help as well.

As far as I know, KiCAD does not have error logs to see what's happening when it tries to load plugin, because even manual installation in `KiCAD\7.0\scripting\plugins\kle-placer` does not fix this issue.

Previously used with KiCAD 6.0.9 and there were no problems at all, but the whole project is on KiCAD 7.0 now, and can't be open with KiCAD 6.0, but I need to update the layout placement, since it all angled, and better just use KLE Placer instead of manually trying to align everything.

Thank you in advance!

![image](https://github.com/zykrah/kicad-kle-placer/assets/31858171/7a3b3074-41d6-4714-9e1e-4f9b5157ff8a)
![image](https://github.com/zykrah/kicad-kle-placer/assets/31858171/a8e12ed4-4e16-4983-8f9a-dcf73656f34d)

**Comment by Iipal** [comment]
PCM still not working correctly, but downloading this repo in .zip and unpacking it to `KiCAD\7.0\scripting\plugins\kle-placer` looks like works fine.

**Comment by zykrah** [comment]
Hi thanks, I'll investigate the PCM.
