### ISSUE TITLE
UnboundLocalerror: local variable 'first_key_pos' referenced before assignment

### ISSUE THREAD

**Issue by dvdcd** [zykrah/kicad-kle-placer#4]
When trying to place switches using Specific Reference Mode (and only in this mode), the script fails and throws this error:
![image](https://user-images.githubusercontent.com/7674825/216780023-52b8dfc1-e2e3-4b79-a820-f3c549214e9b.png)
I fixed it by removing line 326 in the script, saving, and placing again, however that clearly isn't ideal since it doesn't place the keys starting at the first key, it just places them at origin
[keyboard-layout (3).json.txt](https://github.com/zykrah/kicad-kle-placer/files/10609164/keyboard-layout.3.json.txt)
[keyautoplace.log](https://github.com/zykrah/kicad-kle-placer/files/10609180/keyautoplace.log)

Additionally but unrelated, I found it strange that the number locations to place the reference number (noted as 4 in the docs) is inconsistent with the label number in KLE ( a:7 ). Not sure if they changed this on the KLE side but it took me a solid minute to realize what the problem was

**Comment by zykrah** [comment]
Hi, I'll look into the error but the explanation for how KLE handles the `a` property is convoluted, all you need to know is that it should work no matter what the `a` value is, as long as you set the labels in the right spot.

**Comment by zykrah** [comment]
Hi there, looks like the script had a problem finding a footprint with an `MX` reference. I imagine this is because your footprints aren't named that way. You can set the key format using the Key Format box of the plugin run menu. In the meantime, I'll add a more specific error for this. Thanks.

**Comment by zykrah** [comment]
Just re-opening because upon further inspection what I mentioned above doesn't seem like the main issue here. I'll need to know more about how you have your KiCAD project set up. E.g. exactly what it looks like before you attempt to run the code. I have an idea of where the code is missing something but I can't tell why it's missing it without having a look at your KiCAD project.

**Comment by dvdcd** [comment]
They are actually named MX{}, and MX1 does exist:
![image](https://user-images.githubusercontent.com/7674825/216798658-54efbaa0-ba43-47a4-bc8f-6ad212979649.png)
![image](https://user-images.githubusercontent.com/7674825/216798751-6e8aaba1-b30d-42b6-a9e5-652f8ecd0a70.png)

The placer places everything as you'd expect as long as Specific Reference Mode is unchecked and the Key Annotation Format String is changed to MX{}. If I leave it as SW{}, the script fails. If I change the mode to Specific Reference Mode, the placer fails with the same error as above.
Log with failure: [keyautoplace.log](https://github.com/zykrah/kicad-kle-placer/files/10610111/keyautoplace.log)
Log  with success: (with Specific Reference Mode disabled): [keyautoplace.log](https://github.com/zykrah/kicad-kle-placer/files/10610112/keyautoplace.log)

**Comment by dvdcd** [comment]
Ah sorry, my github just refreshed and showed me your comment. My KiCad file is available [here](https://github.com/dvdcd/MA-Command-Keyboard), the issue occurs in both versions. If there's anything super specific you need me to provide, let me know.

Note: the KLE in the github repo is not the one I've been using for the script because the labels are in the wrong spot, the correct one is in my original comment

**Comment by zykrah** [comment]
> My KiCad file is available [here](https://github.com/dvdcd/MA-Command-Keyboard)

Looks like a private repo, can't access it.

**Comment by zykrah** [comment]
Okay, I've just committed to the repo and it should be fixed now. [e2f803b](https://github.com/zykrah/kicad-kle-placer/commit/e2f803b70ef2c161ad75d78b4068716e0fcdeff2). I found some other lingering issues with rotation that I also fixed.

Please try it out and let me know how it goes.

**Comment by dvdcd** [comment]
Works great, Thank you!
