### ISSUE TITLE
plugin does not load (linux with python 3.11)

### ISSUE THREAD

**Issue by robanybody** [zykrah/kicad-kle-placer#6]
on Linux with python 3.11 the plugin does not load
this is the error message I get 

>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
>    return _bootstrap._gcd_import(name[level:], package, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>  File "/home/user/.local/share/kicad/7.0/3rdparty/plugins/com_github_zykrah_kicad-kle-placer/__init__.py", line 1, in 
>  <module>
>    from .kle_placer_action import KLEPlacerAction # Note the relative import!
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/home/user/.local/share/kicad/7.0/3rdparty/plugins/com_github_zykrah_kicad-kle-placer/kle_placer_action.py", line 13, > in <module>
>    from .serial import deserialize, Keyboard
>  File "/home/user/.local/share/kicad/7.0/3rdparty/plugins/com_github_zykrah_kicad-kle-placer/serial.py", line 20, in 
>  <module>
>    @dataclass
>     ^^^^^^^^^
>  File "/usr/lib/python3.11/dataclasses.py", line 1223, in dataclass
>    return wrap(cls)
>           ^^^^^^^^^
>  File "/usr/lib/python3.11/dataclasses.py", line 1213, in wrap
>    return _process_class(cls, init, repr, eq, order, unsafe_hash,
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
>    cls_fields.append(_get_field(cls, name, type, kw_only))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
>    raise ValueError(f'mutable default {type(f.default)} for field '
> ValueError: mutable default <class 'com_github_zykrah_kicad-kle-placer.serial.KeyDefault'> for field default_factory is not 
> allowed: use default_factory

 
Thanks
   Rob

**Comment by robanybody** [comment]
sorry I'm a noob so I have not figured out how to do a merge request 
but I fixed the issue on my machine as far as I can tell
`diff --git a/serial.py b/serial.py
index 56c22d3..ce387a6 100644
--- a/serial.py
+++ b/serial.py
@@ -23,7 +23,7 @@ class Key:
     labels: List[str] = _dcf_list()
     text_color: List[Optional[str]] = _dcf_list()
     text_size: List[Optional[int]] = _dcf_list()
-    default: KeyDefault = KeyDefault()
+    default: KeyDefault = dcf(default_factory=KeyDefault)
     x: float = 0.
     y: float = 0.
     width: float = 1.
@@ -72,7 +72,7 @@ class KeyboardMetadata:
 
 @dataclass
 class Keyboard:
-    meta: KeyboardMetadata = KeyboardMetadata()
+    meta: KeyboardMetadata = dcf(default_factory=KeyboardMetadata)
     keys: List[Key] = _dcf_list()
 
 def get_ndx(lst: list, ndx: int):
`

**Comment by zykrah** [comment]
Thanks, I'll look into it in a bit and I'll add a change to fix.

**Comment by zykrah** [comment]
Changes seemed to work for me fine. Have committed and included the change in the latest release. Thanks!
